services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crud-php-app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: crud_produtos
    depends_on:
      db:
        condition: service_healthy
    networks:
      - minha-rede

  db:
    image: mysql:8.0
    container_name: crud-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud_produtos
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - minha-rede

volumes:
  mysql-data:

networks:
  minha-rede:
    driver: bridge
